<a href="https://colab.research.google.com/github/tthawatch/DPDM/blob/master/Data103_Distance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
A.dot(A.T)

array([[14, 32],
       [32, 77]])

#Array slicing

In [6]:
A[0,1] # เริ่มนับแถวหรือหลักแรกที่ 0

2

In [36]:
A[:,:2] #ข้างหน้าคือแถวที่เราเลือก ข้างหลังคือหลักที่เราจะเลือก _:_ ถ้าไม่ใส่เริ่มจากอันแรกถึงอันสุดท้าย

array([[1, 2],
       [4, 5]])

In [8]:
A[1,1:]

array([5, 6])

In [21]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1 

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [22]:
def Manhattan_dist(dp1,dp2):
  distX = abs(dp1[0]-dp2[0])
  distY = abs(dp1[1]-dp2[1])
  return distX+distY

In [23]:
dist_mat_man = np.zeros((4,4)) # ข้อมูลมีเท่าใดก็จะมีเมตริกตามข้อมูล สร้าง array เปล่า
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
for i in range(4):
  for j in range(4):
     dist_mat_man[i,j] = Manhattan_dist(data1[i,:],data1[j,:])

dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

##HW 6 : สร้าง distance metrix (Euclidean) ของ data matrix ใน slides โดยโครงสร้าง function

In [39]:
import math  

In [40]:
data1 = np.array([[1,2],[3,5],[2,0],[4,5]])
data1 

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [41]:
def Manhattan_dist(dp1,dp2):
  distH = abs(dp1[0]-dp2[0])
  distG = abs(dp1[1]-dp2[1])
  return   math.sqrt(distH**2 + distG**2)


In [42]:
dist_mat_Euclidean = np.zeros((4,4))
dist_mat_Euclidean

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
for i in range(4):
  for j in range(4):
      dist_mat_man[i,j] = Manhattan_dist(data1[i,:],data1[j,:])

dist_mat_man

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])